# Generated by Django 3.0.5 on 2020-05-04 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ACCOUNTS', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='geeksmodel',
            name='amount',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
